### ISSUE TITLE
Add __init__.py file to prevent error in shape_completion.py

### ISSUE THREAD

**Issue by pieterblok** [maurock/DeepSDF#3]
@maurock thank you very much for this nice and clean implementation. 

When running the shape_completion.py code, I noticed an error in lines: https://github.com/maurock/DeepSDF/blob/a64554959ac0cf8ba6cb8525b82db01a002812cf/scripts/shape_completion.py#L23 

https://github.com/maurock/DeepSDF/blob/a64554959ac0cf8ba6cb8525b82db01a002812cf/scripts/shape_completion.py#L44

https://github.com/maurock/DeepSDF/blob/a64554959ac0cf8ba6cb8525b82db01a002812cf/scripts/shape_completion.py#L86

This is happening because there is no `__init__.py` file in folder **DeepSDF/results/runs_sdf** 
Adding the `__init__.py` file resolves the error (maybe you can add it to your repository)

**Comment by maurock** [comment]
Thank you very much @pieterblok, I'll fix this asap!

**Comment by pieterblok** [comment]
> Thank you very much @pieterblok, I'll fix this asap!

Perfect, I'll close the issue!
